export {default as About } from './About'
export {default as MidVid } from './MidVid'
export {default as Movies } from './Movies'
export {default as Testimonial } from './Testimonial'
export {default as Upcoming } from './Upcoming'