export {default as Navbar} from './Navbar/Navbar'
export {default as Footer} from './Footer/Footer'
export {default as Layout} from './Layout'
export {default as Home} from './Home/Home'
export {default as About} from './About/About'
export {default as Movies} from './Movies/Movies'